---
apiVersion: v1
kind: Namespace
metadata:
  name: kubenginxdemo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kdemo
  namespace: kubenginxdemo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: kdemo
    spec:
      containers:
      - name: kdemo
        image: shaker242/dlogo:kdemo
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: false
      #nodeSelector:
        #kubernetes.io/hostname: linux3
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo
  labels:
    name: kdemo
  namespace: kubenginxdemo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: kdemo

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heapster
  namespace: kube-system
spec:
  rules:
  - host: kdemo.kube.docker.ee
    http:
      paths:
      - path: /
        backend:
          serviceName: kdemo
          servicePort: 80