---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kdemo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kdemo
    spec:
      containers:
      - name: kdemo
        image: shaker242/dlogo:kdemo
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: false
      #nodeSelector:
        #kubernetes.io/hostname: linux3
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo
  labels:
    name: kdemo
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 88
    targetPort: 8080
  selector:
    name: kdemo
