version: "3.5"
services:
  dlogo:
    image: dtr.docker.ee/production/webapp:go.26
    deploy:
      resources:
        limits:
          memory: 24M
      mode: replicated
      replicas: 2
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux
    networks:
      - frontend
      - a_frontend
networks:
  frontend:
    driver: overlay
  a_frontend:
    external: true

