version: "3.2"
services:
  dlogo:
    image: dtr.docker.ee/official/webapp:stable
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux
      labels:
        com.docker.lb.hosts: dlogo.apps.docker.ee
        com.docker.lb.network: frontend
        com.docker.lb.port: "80"
    networks:
      - frontend
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 3  
networks:
  frontend:
    driver: overlay