version: "3.5"
services:
  dlogo:
    image: dtr.docker.ee/production/webapp:stable
    deploy:
      resources:
        limits:
          memory: 24M
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
      placement:
        constraints: 
          - node.labels.app==worker
          #- node.platform.os==linux
      labels:
        com.docker.lb.hosts: dlogo.apps.docker.ee
        com.docker.lb.network: interlock
        com.docker.lb.port: "80"
    networks:
      - interlock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      start_period: 10s
      interval: 10s
      timeout: 2s
      retries: 3  
networks:
  interlock:
    external: true

# docker stack deploy -c dlogo.yml webapp