version: "3.5"
services:
  dlogo:
    image: dtr.docker.ee/production/webapp:latest
    deploy:
      resources:
        limits:
          memory: 24M
      mode: replicated
      replicas: 2
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux
          #- node.labels.com.docker.ucp.orchestrator.swarm=true 
      labels:
        com.docker.lb.hosts: dlogo.apps.docker.ee
        com.docker.lb.network: frontend
        com.docker.lb.port: "80"
    networks:
      - frontend
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 3  
networks:
  frontend:
    driver: overlay

# docker stack deploy -c dlogo.yml webapp