version: "3.2"
services:
  web1:
    image: dtr.docker.ee/official/microsoft:iis-nanoserver
    deploy:
      resources:
        limits:
          memory: 64M
      mode: replicated
      replicas: 1
      labels:
        com.docker.lb.hosts: winweb.apps.docker.ee
        com.docker.lb.port: 80
        com.docker.lb.ssl_cert: apps.docker.ee.cert
        com.docker.lb.ssl_key: apps.docker.ee.key
        com.docker.lb.redirects: http://iis.apps.docker.ee,https://iis.apps.docker.ee
    networks: 
      - frontend

networks:
  frontend:
    driver: overlay