version: "3.2"
services:
  moby:
    image: ehazlett/docker-demo
    # ports:
    #   - "8080"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux
      labels:
        com.docker.lb.hosts: whaley.apps.docker.ee
        com.docker.lb.network: frontend
        com.docker.lb.port: "8080"
    networks:
      - frontend

networks:
  frontend:
    driver: overlay