version: "3.2"

services:
  demo:
    image: ehazlett/docker-demo
    ports:
      - "8080"
    deploy:
      replicas: 5
      labels:
        com.docker.lb.hosts: whaley.apps.docker.ee
        com.docker.lb.network: ucp-interlock
        com.docker.lb.port: 8080
    networks:
      - ucp-interlock

networks:
  ucp-interlock:
    external: true