version: "3.5"
services:
  nginx:
    image: nginx:latest
    # ports:
    #   - "37080:8080"
    deploy:
      resources:
        limits:
          memory: 24M
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux
      labels:
        com.docker.lb.hosts: nginx.apps.docker.ee
        com.docker.lb.network: frontend
        com.docker.lb.port: "80"
    networks:
      - frontend
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 3  
networks:
  frontend:
    driver: overlay
