version: "3.2"

networks:
  ucp-interlock:
    external: true

services:
  trustweb:
    image: dtr.docker.ee/trust/whale:0.40
    ports:
      - "8080"
    networks:
      - ucp-interlock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux
      labels:
        com.docker.lb.hosts: trust.apps.docker.ee
        com.docker.lb.network: ucp-interlock
        com.docker.lb.port: "8080"
        com.docker.lb.ssl_cert: apps.docker.ee.cert
        com.docker.lb.ssl_key: apps.docker.ee.key
        com.docker.lb.redirects: http://trust.apps.docker.ee,https://trust.apps.docker.ee
    environment:
      METADATA: proxy-handles-tls
